version: "3.4"

services:
  app:
    container_name: WebRestProvincias
    build: .
    ports:
      - 8090:8090
    network_mode: 'host'
    depends_on:
      - db
  db:
    container_name: SqlServer
    build:
        context: ./db/
    restart: always
    user: root
    volumes:
      - mssql-data:/var/opt/mssql/data
      - mssql-data:/var/opt/mssql/log
      - mssql-data:/var/opt/mssql/secrets
    environment:
      - SA_PASSWORD=${PASSWORD}
      - ACCEPT_EULA=${EULA}
      - MSSQL_PID=${PID}
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G
    ports:
      - 1433:1433
volumes:
  mssql-data: