FROM mcr.microsoft.com/mssql/server:2019-CU10-ubuntu-16.04

USER root

COPY setup.sql setup.sql
COPY import-data.sh import-data.sh
COPY entrypoint.sh entrypoint.sh

RUN chmod +x import-data.sh

USER mssql

ENTRYPOINT /bin/bash ./entrypoint.sh